-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 11:18:31 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hitemni
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hitemni` ;

-- -----------------------------------------------------
-- Schema hitemni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hitemni` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hitemni` ;

-- -----------------------------------------------------
-- Table `hitemni`.`utilisateur_personnalite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`utilisateur_personnalite` (
  `id_utilisateur_personnalite` INT NOT NULL AUTO_INCREMENT,
  `nbr_annee_exp` INT NOT NULL,
  `entreprise_actuelle` VARCHAR(100) NOT NULL,
  `specialite` VARCHAR(45) NOT NULL,
  `type_de_travaille` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utilisateur_personnalite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`CV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`CV` (
  `id_CV` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `intitule` VARCHAR(45) NULL,
  PRIMARY KEY (`id_CV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`preference` (
  `id_preference` INT NOT NULL AUTO_INCREMENT,
  `nom_preference` TINYINT(1) NOT NULL,
  `prenom_preference` TINYINT(1) NOT NULL,
  `adresse_pro_preference` TINYINT(1) NOT NULL,
  `mail_preference` TINYINT(1) NOT NULL,
  `age_preference` TINYINT(1) NOT NULL,
  `promo_preference` TINYINT(1) NOT NULL,
  `telephone_preference` TINYINT(1) NOT NULL,
  `photo_preference` TINYINT(1) NOT NULL,
  `personnalite_preference` TINYINT(1) NOT NULL,
  `cv_preference` TINYINT(1) NOT NULL,
  `sexe_preference` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_preference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `sexe` TINYINT(1) NULL,
  `promo` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(40) NULL,
  `adresse_pro` VARCHAR(45) NULL,
  `photo` VARCHAR(200) NULL,
  `utilisateur_personnalite_fk` INT NOT NULL,
  `CV_fk` INT NOT NULL,
  `preference_fk` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`),
  INDEX `fk_utilisateur_utilisateur_personnalite1_idx` (`utilisateur_personnalite_fk` ASC),
  INDEX `fk_utilisateur_CV1_idx` (`CV_fk` ASC),
  INDEX `fk_utilisateur_preference1_idx` (`preference_fk` ASC),
  CONSTRAINT `fk_utilisateur_utilisateur_personnalite1`
    FOREIGN KEY (`utilisateur_personnalite_fk`)
    REFERENCES `hitemni`.`utilisateur_personnalite` (`id_utilisateur_personnalite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_CV1`
    FOREIGN KEY (`CV_fk`)
    REFERENCES `hitemni`.`CV` (`id_CV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_preference1`
    FOREIGN KEY (`preference_fk`)
    REFERENCES `hitemni`.`preference` (`id_preference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`evenement` (
  `id_evenement` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `descriptif` VARCHAR(200) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_evenement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`techonologie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`techonologie` (
  `id_techonologie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_techonologie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`entreprise` (
  `id_entreprise` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_entreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`entreprise_cv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`entreprise_cv` (
  `id_entreprise_cv` INT NOT NULL AUTO_INCREMENT,
  `CV_id_CV` INT NOT NULL,
  `entreprise_id_entreprise` INT NOT NULL,
  INDEX `fk_entreprise_cv_CV1_idx` (`CV_id_CV` ASC),
  INDEX `fk_entreprise_cv_entreprise1_idx` (`entreprise_id_entreprise` ASC),
  PRIMARY KEY (`id_entreprise_cv`),
  CONSTRAINT `fk_entreprise_cv_CV1`
    FOREIGN KEY (`CV_id_CV`)
    REFERENCES `hitemni`.`CV` (`id_CV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entreprise_cv_entreprise1`
    FOREIGN KEY (`entreprise_id_entreprise`)
    REFERENCES `hitemni`.`entreprise` (`id_entreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`mission` (
  `id_projet` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `descriptif` VARCHAR(250) NOT NULL,
  `date_debut` DATETIME NOT NULL,
  `date_fin` DATETIME NOT NULL,
  `entreprise_cv_fk` INT NOT NULL,
  PRIMARY KEY (`id_projet`),
  INDEX `fk_mission_entreprise_cv1_idx` (`entreprise_cv_fk` ASC),
  CONSTRAINT `fk_mission_entreprise_cv1`
    FOREIGN KEY (`entreprise_cv_fk`)
    REFERENCES `hitemni`.`entreprise_cv` (`id_entreprise_cv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`inscription_evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`inscription_evenement` (
  `id_utilisateur_fk` INT NOT NULL,
  `id_evenement_fk` INT NOT NULL,
  INDEX `fk_utilisateur_has_evenment_evenment1_idx` (`id_evenement_fk` ASC),
  INDEX `fk_utilisateur_has_evenment_utilisateur1_idx` (`id_utilisateur_fk` ASC),
  PRIMARY KEY (`id_utilisateur_fk`, `id_evenement_fk`),
  CONSTRAINT `fk_utilisateur_has_evenment_utilisateur1`
    FOREIGN KEY (`id_utilisateur_fk`)
    REFERENCES `hitemni`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_evenment_evenment1`
    FOREIGN KEY (`id_evenement_fk`)
    REFERENCES `hitemni`.`evenement` (`id_evenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`cv_technologie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`cv_technologie` (
  `CV_fk` INT NOT NULL,
  `techonologie_fk` INT NOT NULL,
  INDEX `fk_CV_has_techonologie_techonologie1_idx` (`techonologie_fk` ASC),
  INDEX `fk_CV_has_techonologie_CV1_idx` (`CV_fk` ASC),
  PRIMARY KEY (`CV_fk`, `techonologie_fk`),
  CONSTRAINT `fk_CV_has_techonologie_CV1`
    FOREIGN KEY (`CV_fk`)
    REFERENCES `hitemni`.`CV` (`id_CV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CV_has_techonologie_techonologie1`
    FOREIGN KEY (`techonologie_fk`)
    REFERENCES `hitemni`.`techonologie` (`id_techonologie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`cv_mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`cv_mission` (
  `CV_fk` INT NOT NULL,
  `projet_fk` INT NOT NULL,
  PRIMARY KEY (`CV_fk`, `projet_fk`),
  INDEX `fk_CV_has_projet_projet1_idx` (`projet_fk` ASC),
  INDEX `fk_CV_has_projet_CV1_idx` (`CV_fk` ASC),
  CONSTRAINT `fk_CV_has_projet_CV1`
    FOREIGN KEY (`CV_fk`)
    REFERENCES `hitemni`.`CV` (`id_CV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CV_has_projet_projet1`
    FOREIGN KEY (`projet_fk`)
    REFERENCES `hitemni`.`mission` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hitemni`.`entreprise_mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hitemni`.`entreprise_mission` (
  `entreprise_fk` INT NOT NULL,
  `mission_fk` INT NOT NULL,
  PRIMARY KEY (`entreprise_fk`, `mission_fk`),
  INDEX `fk_entreprise_has_mission_mission1_idx` (`mission_fk` ASC),
  INDEX `fk_entreprise_has_mission_entreprise1_idx` (`entreprise_fk` ASC),
  CONSTRAINT `fk_entreprise_has_mission_entreprise1`
    FOREIGN KEY (`entreprise_fk`)
    REFERENCES `hitemni`.`entreprise` (`id_entreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entreprise_has_mission_mission1`
    FOREIGN KEY (`mission_fk`)
    REFERENCES `hitemni`.`mission` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
